### ISSUE TITLE
这个是解析官网提供的二进制吗？

### ISSUE THREAD

**Issue by semgilo** [zhongfq/spine-binaryreader#2]
还是将json读出来写出自己的二进制文件，然后再去读呢？读官网我看了一下是读不出来  目前我的版本是2.1.17  看名字应该中文是有办法看懂吧

**Comment by codetypess** [comment]
我之前因为时间紧张，没有使用官方的二进制格式，使用了自己的二进制。不过最重要的是我对spine的动画进行插补帧，解决混合动画错乱的问题，如果有需要的话，我找个时间导出官方的二进制格式和JSON格式

**Comment by semgilo** [comment]
我有需要  非常感谢

**Comment by codetypess** [comment]
你的需求是怎么样子的呢？

**Comment by semgilo** [comment]
我就是想用二进制，因为json1M多速度实在是慢得不行，我现在是把官网的解析出来，但风格会有拉长，就是SP_ATTACHMENT_SKINNED_MESH这个读取的striangles的值不对 ，虽然可以正常运行。9737935 QQ 如果方便加我一下

**Comment by codetypess** [comment]
我最近比较忙，可能还没有时间弄，你可以参考我的格式，自己改一改

**Comment by codetypess** [comment]
已经更新了二进制库了，改为支持官方的二进制格式，但spine库，必须使用最新的

**Comment by semgilo** [comment]
好的，之前我自己参照几个版本也弄一个支持官方的版本出来
